<template><div><h1 id="九、mybatisx-插件" tabindex="-1"><a class="header-anchor" href="#九、mybatisx-插件"><span>九、MybatisX 插件</span></a></h1>
<p><img src="https://cdn.nlark.com/yuque/0/2023/png/34476449/1672644065642-c5187792-99e4-4826-ae08-6957a4d239d2.png#averageHue=%23d5a764&amp;clientId=ud880c310-d818-4&amp;from=paste&amp;height=709&amp;id=u2ca9c34d&amp;originHeight=886&amp;originWidth=1226&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=68773&amp;status=done&amp;style=shadow&amp;taskId=u33dffae8-a0bb-468b-9126-153554382f8&amp;title=&amp;width=980.8" alt="image.png"></p>
<blockquote>
<p>主要作用：</p>
<ol>
<li>将 Mapper 接口和映射文件进行对应</li>
</ol>
<p><img src="https://cdn.nlark.com/yuque/0/2023/png/34476449/1672644227524-4f26b50b-334d-4e29-a768-c2daf1061367.png#averageHue=%23f6f2e0&amp;clientId=ud880c310-d818-4&amp;from=paste&amp;height=29&amp;id=u8a43b9f7&amp;originHeight=36&amp;originWidth=1151&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=13810&amp;status=done&amp;style=shadow&amp;taskId=ud97ec8e1-c9f8-467b-ae88-76ffee7a5fa&amp;title=&amp;width=920.8" alt="image.png">
<img src="https://cdn.nlark.com/yuque/0/2023/png/34476449/1672644248278-38862dad-446a-40ab-9f39-c9d995838a94.png#averageHue=%23f8f3e5&amp;clientId=ud880c310-d818-4&amp;from=paste&amp;height=80&amp;id=u0567b1b6&amp;originHeight=100&amp;originWidth=656&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=20372&amp;status=done&amp;style=shadow&amp;taskId=ud40d9179-7e17-4610-889e-5c85ee23597&amp;title=&amp;width=524.8" alt="image.png"></p>
</blockquote>
<h2 id="_1、使用-mybatisx-生成代码" tabindex="-1"><a class="header-anchor" href="#_1、使用-mybatisx-生成代码"><span>1、使用 MybatisX 生成代码</span></a></h2>
<blockquote>
<p>使用 MybatisX 生成 mapper 接口、mapper 映射文件、Service 和实体类。</p>
</blockquote>
<p><strong>在 IDEA 中配置数据源</strong>
<img src="https://cdn.nlark.com/yuque/0/2023/png/34476449/1672645422882-313224c5-4585-4e8f-919c-892227b153cb.png#averageHue=%23f4f3f1&amp;clientId=ud880c310-d818-4&amp;from=paste&amp;height=258&amp;id=u0957a9a0&amp;originHeight=322&amp;originWidth=662&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=34096&amp;status=done&amp;style=shadow&amp;taskId=u27b44a57-b944-4e42-9022-ccdaf7171a6&amp;title=&amp;width=529.6" alt="image.png">
<img src="https://cdn.nlark.com/yuque/0/2023/png/34476449/1672645488480-e5438805-084c-4378-9b9c-46f7d25c2f87.png#averageHue=%23d6ab6b&amp;clientId=ud880c310-d818-4&amp;from=paste&amp;height=674&amp;id=u5a3a216b&amp;originHeight=843&amp;originWidth=1000&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=50763&amp;status=done&amp;style=shadow&amp;taskId=ud5c91fd9-8a2c-4877-b5cd-c039c3e6a82&amp;title=&amp;width=800" alt="image.png">
配置成功后，显示如下：
<img src="https://cdn.nlark.com/yuque/0/2023/png/34476449/1672645522337-9534fedf-d80e-44aa-8444-6cf240ea9048.png#averageHue=%23d8af6e&amp;clientId=ud880c310-d818-4&amp;from=paste&amp;height=157&amp;id=ud590682e&amp;originHeight=196&amp;originWidth=660&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=17146&amp;status=done&amp;style=shadow&amp;taskId=ufa02669f-2c73-4a1e-a174-edb191850bc&amp;title=&amp;width=528" alt="image.png">
<strong>使用代码生成器</strong>
<img src="https://cdn.nlark.com/yuque/0/2023/png/34476449/1672645549218-b29371fb-e361-4c62-9361-8557e4acfb9e.png#averageHue=%23f3f2f2&amp;clientId=ud880c310-d818-4&amp;from=paste&amp;height=104&amp;id=uedbb4ce1&amp;originHeight=130&amp;originWidth=661&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=11713&amp;status=done&amp;style=shadow&amp;taskId=ue1503152-3eab-405c-bbf8-662057b9444&amp;title=&amp;width=528.8" alt="image.png">
<img src="https://cdn.nlark.com/yuque/0/2023/png/34476449/1672645337144-11dfb715-dc13-4610-991b-403b7051659b.png#averageHue=%23f6f5f5&amp;clientId=ud880c310-d818-4&amp;from=paste&amp;height=494&amp;id=u8588b49f&amp;originHeight=618&amp;originWidth=1119&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=28656&amp;status=done&amp;style=shadow&amp;taskId=uc4b962a4-6e1a-4b99-86af-91334915ed4&amp;title=&amp;width=895.2" alt="image.png">
<img src="https://cdn.nlark.com/yuque/0/2023/png/34476449/1672645219874-6d56d747-8990-434d-b82d-2e7292250d82.png#averageHue=%23f2f1f0&amp;clientId=ud880c310-d818-4&amp;from=paste&amp;height=490&amp;id=u5a9fe9c3&amp;originHeight=613&amp;originWidth=1124&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=44411&amp;status=done&amp;style=shadow&amp;taskId=u3324c5b9-346d-465f-8ebc-e07c964be36&amp;title=&amp;width=899.2" alt="image.png">
生成完毕后，再根据需求进行修改。</p>
<h2 id="_2、使用-mybatisx-生成-crud" tabindex="-1"><a class="header-anchor" href="#_2、使用-mybatisx-生成-crud"><span>2、使用 MybatisX 生成 CRUD</span></a></h2>
<p>在 mapper 接口中添加方法时，MybatisX 会提示一些方法，使用这些方法可以自动生成 mapper 映射文件。
<img src="https://cdn.nlark.com/yuque/0/2023/png/34476449/1672646114700-a9a07537-e15c-4c42-9fa5-5bba11f03e56.png#averageHue=%23eae8e1&amp;clientId=ud880c310-d818-4&amp;from=paste&amp;height=50&amp;id=ua9f3c4dc&amp;originHeight=62&amp;originWidth=630&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=5961&amp;status=done&amp;style=shadow&amp;taskId=uf8b6b44b-878e-472a-b99e-e6f16f19af9&amp;title=&amp;width=504" alt="image.png">
<img src="https://cdn.nlark.com/yuque/0/2023/png/34476449/1672646142589-799e6323-3e46-4f87-9bd2-dd0766a7fd13.png#averageHue=%23fbf9ec&amp;clientId=ud880c310-d818-4&amp;from=paste&amp;height=54&amp;id=u322f5e69&amp;originHeight=68&amp;originWidth=589&amp;originalType=binary&amp;ratio=1&amp;rotation=0&amp;showTitle=false&amp;size=5558&amp;status=done&amp;style=shadow&amp;taskId=u48d636b8-ccdd-4a75-a6b0-8108c210c32&amp;title=&amp;width=471.2" alt="image.png">
生成的 SQL 如下：</p>
<div class="language-xml line-numbers-mode" data-highlighter="prismjs" data-ext="xml" data-title="xml"><pre v-pre><code><span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>insert</span> <span class="token attr-name">id</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>insertSelective<span class="token punctuation">"</span></span><span class="token punctuation">></span></span></span>
<span class="line">  insert into t_user</span>
<span class="line">  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>trim</span> <span class="token attr-name">prefix</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>(<span class="token punctuation">"</span></span> <span class="token attr-name">suffix</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>)<span class="token punctuation">"</span></span> <span class="token attr-name">suffixOverrides</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>,<span class="token punctuation">"</span></span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>id != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>id,<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>name != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>name,<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>age != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>age,<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>email != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>email,<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>isDeleted != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>is_deleted,<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sex != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>sex,<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>trim</span><span class="token punctuation">></span></span></span>
<span class="line">  values</span>
<span class="line">  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>trim</span> <span class="token attr-name">prefix</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>(<span class="token punctuation">"</span></span> <span class="token attr-name">suffix</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>)<span class="token punctuation">"</span></span> <span class="token attr-name">suffixOverrides</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>,<span class="token punctuation">"</span></span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>id != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>#{id,jdbcType=BIGINT},<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>name != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>#{name,jdbcType=VARCHAR},<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>age != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>#{age,jdbcType=INTEGER},<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>email != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>#{email,jdbcType=VARCHAR},<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>isDeleted != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>#{isDeleted,jdbcType=INTEGER},<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">    <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>if</span> <span class="token attr-name">test</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>sex != null<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>#{sex,jdbcType=INTEGER},<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>if</span><span class="token punctuation">></span></span></span>
<span class="line">  <span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>trim</span><span class="token punctuation">></span></span></span>
<span class="line"><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>insert</span><span class="token punctuation">></span></span></span>
<span class="line"></span></code></pre>
<div class="line-numbers" aria-hidden="true" style="counter-reset:line-number 0"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


